updated db

diff --git a/bin/insta485db b/bin/insta485db
--- a/bin/insta485db
+++ b/bin/insta485db
@@ -7,7 +7,7 @@ set -Eeuo pipefail
 
 # Sanity check command line options
 usage() {
-  echo "Usage: $0 (create|destroy|reset|dump)"
+  echo "Usage: $0 (create|destroy|reset|dump|random)"
 }
 
 if [ $# -ne 1 ]; then
@@ -15,38 +15,69 @@ if [ $# -ne 1 ]; then
   exit 1
 fi
 
-# Parse argument.  $1 is the first argument
+# Parse argument. $1 is the first argument
 case $1 in
   "create")
-          if [ -f var/insta485.sqlite3 ]; then
-              echo "Error: database already exists"
-              exit 1
-            fi
-          mkdir -p var/uploads
-          sqlite3 var/insta485.sqlite3 < sql/schema.sql
-          sqlite3 var/insta485.sqlite3 < sql/data.sql
-          cp sql/uploads/* var/uploads/
+    if [ -f var/insta485.sqlite3 ]; then
+      echo "Error: database already exists"
+      exit 1
+    fi
+    mkdir -p var/uploads
+    sqlite3 var/insta485.sqlite3 < sql/schema.sql
+    sqlite3 var/insta485.sqlite3 < sql/data.sql
+    cp sql/uploads/* var/uploads/
     ;;
 
   "destroy")
-          rm -rf var/insta485.sqlite3 var/uploads
+    rm -rf var/insta485.sqlite3 var/uploads
     ;;
 
   "reset")
-          rm -rf var/insta485.sqlite3 var/uploads
-          mkdir -p var/uploads
-          sqlite3 var/insta485.sqlite3 < sql/schema.sql
-          sqlite3 var/insta485.sqlite3 < sql/data.sql
-          cp sql/uploads/* var/uploads/
+    rm -rf var/insta485.sqlite3 var/uploads
+    mkdir -p var/uploads
+    sqlite3 var/insta485.sqlite3 < sql/schema.sql
+    sqlite3 var/insta485.sqlite3 < sql/data.sql
+    cp sql/uploads/* var/uploads/
     ;;
 
   "dump")
-          sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM users'
-          sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM posts'
-          sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM comments'
-          sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM following'
-          sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM likes'
+    sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM users'
+    sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM posts'
+    sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM comments'
+    sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM following'
+    sqlite3 -batch -line var/insta485.sqlite3 'SELECT * FROM likes'
     ;;
+
+  "random")
+    DB_FILENAME=var/insta485.sqlite3
+
+    if command -v magick &> /dev/null; then
+      IM_CMD="magick"
+    elif command -v convert &> /dev/null; then
+      IM_CMD="convert"
+    else
+      echo "Error: Neither 'magick' nor 'convert' command found."
+      exit 1
+    fi
+
+    mkdir -p var/uploads
+
+    for i in `seq 1 100`; do
+      FILENAME="$(uuidgen).png"
+      NUMS=()
+      for j in `seq 1 6`; do
+        NUMS+=($(($RANDOM % 255)))
+      done
+      "$IM_CMD" -size 360x360 \
+        radial-gradient:"rgb(${NUMS[0]},${NUMS[1]},${NUMS[2]})-rgb(${NUMS[3]},${NUMS[4]},${NUMS[5]})" \
+        -pointsize 64 -fill black -gravity center \
+        -annotate 0 "image $i" "var/uploads/$FILENAME"
+      OWNER="awdeorio"
+      sqlite3 -echo -batch ${DB_FILENAME} \
+        "INSERT INTO posts(filename, owner) VALUES('${FILENAME}','${OWNER}');"
+    done
+    ;;
+
   *)
     usage
     exit 1
